apiVersion: v1
kind: Service
metadata:
  name: veidemann-harvester
  labels:
    app.kubernetes.io/name: veidemann-harvester
    app.kubernetes.io/component: harvester
spec:
  type: ClusterIP
  ports:
    - name: debug
      port: 3000
      protocol: TCP
      targetPort: debug
    - name: proxy
      port: 8080
      protocol: TCP
      targetPort: proxy
    - name: http-metrics
      port: 9301
      protocol: TCP
      targetPort: http-metrics
  selector:
    app.kubernetes.io/name: veidemann-harvester
    app.kubernetes.io/component: harvester
