apiVersion: apps/v1
kind: Deployment
metadata:
  name: rethinkdb-admin
  labels:
    app.kubernetes.io/name: rethinkdb
    app.kubernetes.io/component: dashboard
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rethinkdb
      app.kubernetes.io/component: dashboard
  template:
    metadata:
      name: rethinkdb-admin
      labels:
        app.kubernetes.io/name: rethinkdb
        app.kubernetes.io/component: dashboard
    spec:
      serviceAccountName: rethinkdb
      containers:
        - name: rethinkdb-admin
          image: codylundquist/helm-rethinkdb-cluster:0.1.0
          ports:
            - name: cluster
              containerPort: 29015
            - name: driver
              containerPort: 28015
            - name: http-admin
              containerPort: 8080
          args:
            - --bind
            - $(POD_IP)
            - --no-update-check
          volumeMounts:
            - name: secrets
              mountPath: /secrets
          env:
            - name: PROXY
              value: "true"
            - name: RETHINK_CLUSTER_SERVICE
              value: $(RETHINK_CLUSTER_SERVICE_NAME)
            - name: RETHINKDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rethinkdb
                  key: rethinkdb-password
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          startupProbe:
            exec:
              command:
                - /rethinkdb-probe
            failureThreshold: 10
          livenessProbe:
            exec:
              command:
                - /rethinkdb-probe
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - /rethinkdb-probe
            timeoutSeconds: 5
      volumes:
        - name: secrets
          secret:
            secretName: rethinkdb
