apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jaeger-ingressroute
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`veidemann.local`) && PathPrefix(`/jaeger`)
      kind: Rule
      services:
        - name: jaeger-query
          port: 16686
  tls: {}
