apiVersion: apps/v1
kind: Deployment
metadata:
  name: veidemann-robotsevaluator-service
  labels:
    app.kubernetes.io/name: veidemann-robotsevaluator
    app.kubernetes.io/component: robotsevaluator
  annotations:
    sidecar.jaegertracing.io/inject: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: veidemann-robotsevaluator
      app.kubernetes.io/component: robotsevaluator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: veidemann-robotsevaluator
        app.kubernetes.io/component: robotsevaluator
      annotations:
        # config.linkerd.io/opaque-ports: "8080"
        linkerd.io/inject: enabled
    spec:
      volumes:
        - name: log4j2
          configMap:
            name: veidemann-robotsevaluator
            items:
              - key: log4j2.xml
                path: log4j2.xml
      containers:
        - name: veidemann-robotsevaluator-service
          image: norsknettarkiv/veidemann-robotsevaluator-service:0.4.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 7053
              protocol: TCP
          envFrom:
            - secretRef:
                name: rethinkdb-env
                optional: false
          env:
            - name: DB_HOST
              value: "rethinkdb-proxy"
            - name: DB_PORT
              value: "28015"
            - name: DB_NAME
              value: "veidemann"
            - name: API_PORT
              value: "7053"
            - name: PROXY_HOST
              value: veidemann-harvester
            - name: PROXY_PORT
              value: "8080"
            - name: JAEGER_SERVICE_NAME
              value: veidemann-robotsevaluator-service
            - name: JAEGER_AGENT_HOST
              value: localhost
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: JAEGER_SAMPLER_TYPE
              value: remote
            - name: JAEGER_SAMPLER_PARAM
              value: "0.1"
            - name: JAVA_TOOL_OPTIONS
              value: -Dfile.encoding=UTF-8
            - name: JAEGER_PROPAGATION
              value: jaeger,b3
          volumeMounts:
            - mountPath: /veidemann/config/log4j2.xml
              name: log4j2
              subPath: log4j2.xml
