apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: prometheus-stripprefix
  namespace: monitoring
spec:
  stripPrefix:
    prefixes:
      - /prometheus
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kube-prometheus-ingressroute
  namespace: monitoring
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`veidemann.local`) && PathPrefix(`/grafana`)
      kind: Rule
      services:
        - name: grafana
          port: 3000
    - match: Host(`veidemann.local`) && PathPrefix(`/prometheus`)
      kind: Rule
      middlewares:
        - name: prometheus-stripprefix
      services:
        - name: prometheus-k8s
          port: 9090
  tls:
    secretName: veidemann-ingress-tls-cert
