apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-servicemonitor
  namespace: monitoring
spec:
  endpoints:
  - path: /metrics
    port: exporter
  jobLabel: redis
  namespaceSelector:
    matchNames:
    - veidemann
  selector:
    matchLabels:
      redis: veidemann-frontier
    matchExpressions:
      - key: role
        operator: NotIn
        values:
          - master
      - key: service-type
        operator: NotIn
        values:
          - headless
