apiVersion: apps/v1
kind: Deployment
metadata:
  name: veidemann-dns-resolver
  labels:
    app.kubernetes.io/name: veidemann-dns-resolver
    app.kubernetes.io/component: dns-resolver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: veidemann-dns-resolver
      app.kubernetes.io/component: dns-resolver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: veidemann-dns-resolver
        app.kubernetes.io/component: dns-resolver
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: veidemann-dns-resolver
          image: norsknettarkiv/veidemann-dns-resolver:0.2.7
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: veidemann-rethinkdb-env
                optional: false
          env:
            - name: DB_HOST
              value: "rethinkdb-proxy"
            - name: DB_PORT
              value: "28015"
            - name: DB_NAME
              value: "veidemann"
            - name: CONTENT_WRITER_HOST
              value: "veidemann-contentwriter"
            - name: CONTENT_WRITER_PORT
              value: "8082"
            - name: DNS_SERVER
              value: 8.8.8.8
          ports:
            - containerPort: 8053
              name: grpc
              protocol: TCP
            - containerPort: 53
              name: dns
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 9153
              name: http-metrics
              protocol: TCP
            - containerPort: 8080
              name: http-health
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http-health
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http-health
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
