apiVersion: apps/v1
kind: Deployment
metadata:
  name: veidemann-log-service
  labels:
    app.kubernetes.io/name: veidemann-log-service
    app.kubernetes.io/component: log-service
  annotations:
    sidecar.jaegertracing.io/inject: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: veidemann-log-service
      app.kubernetes.io/component: log-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: veidemann-log-service
        app.kubernetes.io/component: log-service
      annotations:
        # shard awereness fails if linkerd is enabled
        linkerd.io/inject: disabled
        # skip outbound to scylla
        linkerd.io/skip-outbound-ports: "9042,19042"
    spec:
      containers:
        - name: veidemann-log-service
          image: norsknettarkiv/veidemann-log-service:v0.1.6
          ports:
            - name: grpc
              containerPort: 8080
              protocol: TCP
            - name: http-metrics
              containerPort: 9153
              protocol: TCP
          env:
            - name: PORT
              value: "8080"
            - name: LOG_LEVEL
              value: "debug"
            - name: DB_HOST
              value: "scylla-0.scylla"
            - name: DB_KEYSPACE
              value: "v7n_v1_dc1"
            - name: JAEGER_SERVICE_NAME
              value: veidemann-log-service
            - name: JAEGER_AGENT_HOST
              value: localhost
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: JAEGER_SAMPLER_TYPE
              value: remote
            - name: JAEGER_SAMPLER_PARAM
              value: "0.1"
