kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: ingress-traefik
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
      app: traefik
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traefik
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.0
          ports:
            - name: websecure
              containerPort: 443
              hostPort: 443
            - name: admin
              containerPort: 8080
              hostPort: 8080
          volumeMounts:
            - mountPath: /etc/traefik
              name: traefik-static-config
            - mountPath: /config
              name: traefik-dynamic-config
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Equal
          effect: NoSchedule
      volumes:
        - name: traefik-static-config
          configMap:
            name: traefik-static-config
        - name: traefik-dynamic-config
          configMap:
            name: traefik-dynamic-config
