apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
  labels:
    app.kubernetes.io/name: dex
    app.kubernetes.io/component: idp
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: dex
      app.kubernetes.io/component: idp
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dex
        app.kubernetes.io/component: idp
    spec:
      serviceAccount: dex
      serviceAccountName: dex
      nodeSelector: {}
      terminationGracePeriodSeconds: 30

      containers:
      - name: main
        image: quay.io/dexidp/dex:v2.19.0
        imagePullPolicy: IfNotPresent
        command:
        - /usr/local/bin/dex
        - serve
        - /etc/dex/cfg/config.yaml
        resources: {}
          
        ports:
        - name: http
          containerPort: 5556
          protocol: TCP
        - name: grpc
          containerPort: 5000
          protocol: TCP
        env: []
          
        volumeMounts:
        - mountPath: /etc/dex/cfg
          name: config

      volumes:
      - secret:
          defaultMode: 420
          items:
          - key: config.yaml
            path: config.yaml
          secretName: dex
        name: config
