kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - serviceaccount.yaml

commonLabels:
  app.kubernetes.io/name: dex
  app.kubernetes.io/instance: dex
  app.kubernetes.io/component: idp
  app.kubernetes.io/part-of: veidemann

secretGenerator:
  - name: dex
    files:
      - config.yaml
