apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../cert
  - redis_frontier.yaml
  - ../dex
  - ../../../bases/rethinkdb
  - ../../../bases/rethinkdb-exporter
  - ../../../bases/veidemann-db-initializer
  - ../../../bases/veidemann-metrics
  - ../../../bases/veidemann-dns-resolver
  - ../../../bases/veidemann-controller
  - ../../../bases/veidemann-frontier
  - ../../../bases/veidemann-contentwriter
  - ../../../bases/veidemann-cache
  - ../../../bases/veidemann-robotsevaluator
  - ../../../bases/veidemann-scopeservice
  - ../../../bases/veidemann-harvester
  - ../../../bases/veidemann-dashboard
  - ../../../bases/veidemann-warcvalidator
  - ../../../bases/veidemann-ooshandler
  - ../../../bases/veidemann-health-check-api
  - ../../../bases/rethinkdb-backup
  - ingressroute.yaml
  - persistence/

namespace: veidemann

patchesStrategicMerge:
  - cache-balancer_env_patch.yaml
  - cache_env_patch.yaml
  - contentwriter_env_patch.yaml
  - contentwriter_volume_patch.yaml
  - controller_ca_patch.yaml
  - controller_env_patch.yaml
  - controller_volume_patch.yaml
  - db-initializer_env_patch.yaml
  - dnsresolver_env_patch.yaml
  - frontier_env_patch.yaml
  - harvester_env_patch.yaml
  - health-check_env_patch.yaml
  - metrics_env_patch.yaml
  - ooshandler_volume_patch.yaml
  - rethinkdb-exporter_env_patch.yaml
  - rethinkdb_backup_env_patch.yaml
  - rethinkdb_backup_volume_patch.yaml
  - robotsevaluator_env_patch.yaml
  - warcvalidator_volume_patch.yaml
  - harvester_log_level_patch.yaml
  - dashboard_patch.yaml

secretGenerator:
  - name: veidemann-env
    literals:
      - CONTROLLER_API_KEY=ABCD-1234
      - apiKeyRoleMapping.txt=ABCD-1234 ADMIN
  - name: veidemann-rethinkdb-env
    literals:
      - DB_USER=admin
      - DB_PASSWORD=rethinkdb
  - name: rethinkdb
    behavior: replace
    literals:
      - rethinkdb-password=rethinkdb

configMapGenerator:
  - name: veidemann
    files:
      - log4j2.xml
    literals:
      - openidConnectIssuer=https://veidemann.local/dex
  - name: veidemann-version
    literals:
      - versions.json={"veidemann":"dev"}
  - name: veidemann-dashboard-environment
    behavior: replace
    files:
      - environment.json

vars:
  # Get service names.
  - name: DB_SERVICE_NAME
    objref:
      kind: Service
      apiVersion: v1
      name: rethinkdb-proxy
  - name: CONTROLLER_SERVICE_NAME
    objref:
      kind: Service
      apiVersion: v1
      name: veidemann-controller
  - name: FRONTIER_SERVICE_NAME
    objref:
      kind: Service
      apiVersion: v1
      name: veidemann-frontier
  - name: ROBOTS_EVALUATOR_SERVICE_NAME
    objref:
      kind: Service
      apiVersion: v1
      name: veidemann-robotsevaluator-service
  - name: DNS_RESOLVER_SERVICE_NAME
    objref:
      kind: Service
      apiVersion: v1
      name: veidemann-dns-resolver
  - name: CONTENT_WRITER_SERVICE_NAME
    objref:
      kind: Service
      apiVersion: v1
      name: veidemann-contentwriter
  - name: CACHE_BALANCER_SERVICE_NAME
    objref:
      kind: Service
      apiVersion: v1
      name: veidemann-cache-balancer
  - name: CACHE_SERVICE_NAME
    objref:
      kind: Service
      apiVersion: v1
      name: veidemann-cache
  - name: HARVESTER_SERVICE_NAME
    objref:
      kind: Service
      apiVersion: v1
      name: veidemann-harvester
  - name: OOS_HANDLER_SERVICE_NAME
    objref:
      kind: Service
      apiVersion: v1
      name: veidemann-ooshandler
  - name: DASHBOARD_SERVICE_NAME
    objref:
      kind: Service
      apiVersion: v1
      name: veidemann-dashboard
  - name: SCOPESERVICE_SERVICE_NAME
    objref:
      kind: Service
      apiVersion: v1
      name: veidemann-scopeservice
