apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/instance: veidemann-contentwriter
  app.kubernetes.io/part-of: veidemann

configMapGenerator:
  - name: veidemann-contentwriter
    files:
      - log4j2.xml
