apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-ingressroute
  namespace: ingress-traefik
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`veidemann.local`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      kind: Rule
      priority: 12
      services:
        - name: traefik
          port: 8080
  tls:
    secretName: veidemann-ingress-tls-cert
