apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/instance: veidemann-controller
  app.kubernetes.io/part-of: veidemann

configmapGenerator:
  - name: veidemann-controller-envoy
    files:
      - envoy.yaml
