apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - rolebinding.yaml
  - service.yaml
  - deployment.yaml
  - statefulset.yaml

commonLabels:
  app.kubernetes.io/instance: veidemann-cache
  app.kubernetes.io/part-of: veidemann

secretGenerator:
  - name: veidemann-cache
    options:
      disableNameSuffixHash: true
    type: Opaque
    files:
      - cert/cache-selfsigned.key
      - cert/cache-selfsignedCA.crt
      - cert/ec.param
