apiVersion: v1
kind: Service
metadata:
  name: veidemann-cache-balancer
  labels:
    app.kubernetes.io/name: veidemann-cache
    app.kubernetes.io/component: cache-balancer
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3128
    protocol: TCP
    targetPort: http
  - name: http-metrics
    port: 9301
    protocol: TCP
    targetPort: http-metrics
  selector:
    app.kubernetes.io/name: veidemann-cache
    app.kubernetes.io/component: cache-balancer
---

apiVersion: v1
kind: Service
metadata:
  name: veidemann-cache
  labels:
    app.kubernetes.io/name: veidemann-cache
    app.kubernetes.io/component: cache
spec:
  type: ClusterIP
  ports:
    - port: 3128
      targetPort: http
      protocol: TCP
      name: http
    - port: 9301
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    app.kubernetes.io/name: veidemann-cache
    app.kubernetes.io/component: cache
